version: '3.3'

networks:
  business-intelligence-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

## --------------------------------------------- DASHBOARD SECTION --------------------------------------------
  # Container Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "0"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    restart: unless-stopped
    links:
      - postgres
    expose:
      - 3000
    networks:
      - business-intelligence-net
    labels:
      org.label-schema.group: "business-intelligence"
## ------------------------------------------- END DASHBOARD SECTION ------------------------------------------


## --------------------------------------------- POSTGRES SECTION ---------------------------------------------
  # Database Container (postgres)
  postgres:
    container_name: pg_container
    image: postgres:12.10
    restart: always
    environment:
      POSTGRES_USER: shoc
      POSTGRES_PASSWORD: shoc
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - business-intelligence-net

  # Container of PGAdmin (web-based admin tool for postgres database)
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: shoc@shoc.us
      PGADMIN_DEFAULT_PASSWORD: shoc@shoc.us
    links:
      - postgres
    ports:
      - "3031:80"
    networks:
      - business-intelligence-net
## ------------------------------------------- END POSTGRES SECTION -------------------------------------------



