{
 "title": "UFO Data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sightings by State",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT r.id AS report_id,\r\n       co.name AS country_name,\r\n       st.name AS state_name,\r\n       st.name AS state_count\r\nFROM reports r \r\nLEFT JOIN countries co ON r.country_id = co.id\r\nLEFT JOIN states st ON r.state_id = st.id"
    }
   ]
  },
  {
   "title": "Sightings across the World",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT co.name AS country_name,\r\nco.name AS country_count\r\nFROM reports r \r\nLEFT JOIN countries co ON r.country_id = co.id\r\nLEFT JOIN states st ON r.state_id = st.id"
    }
   ]
  },
  {
   "title": "Quantified Sightings by State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n       co.name AS country_name,\r\n       st.name AS state_name,\r\n       st.name AS state_count\r\nFROM reports r \r\nLEFT JOIN countries co ON r.country_id = co.id\r\nLEFT JOIN states st ON r.state_id = st.id"
    }
   ]
  },
  {
   "title": "UFO Sightings by Year (Linear)",
   "type": "trend",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(YEAR FROM event_date) AS year,\r\n       COUNT(*) AS count\r\nFROM reports\r\nGROUP BY EXTRACT(YEAR FROM event_date)\r\nORDER BY year ASC;"
    }
   ]
  },
  {
   "title": "UFO Sightings by Year (Logarithmic)",
   "type": "trend",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(YEAR FROM event_date) AS year,\r\n       COUNT(*) AS count\r\nFROM reports\r\nGROUP BY EXTRACT(YEAR FROM event_date)\r\nORDER BY year ASC;"
    }
   ]
  },
  {
   "title": "Sightings by Month",
   "type": "trend",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(MONTH FROM event_date) AS month,\r\n       COUNT(*) AS count\r\nFROM reports\r\nGROUP BY EXTRACT(MONTH FROM event_date)\r\nORDER BY month ASC;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "trend",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(DAY FROM event_date) AS day,\r\n       COUNT(*) AS count\r\nFROM reports\r\nGROUP BY EXTRACT(DAY FROM event_date)\r\nORDER BY day ASC;"
    }
   ]
  },
  {
   "title": "UFO Sightings by Hour",
   "type": "trend",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(HOUR FROM event_date) AS hour,\r\n       COUNT(*) AS count\r\nFROM reports\r\nGROUP BY EXTRACT(HOUR FROM event_date)\r\nORDER BY hour ASC;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "trend",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(MINUTE FROM event_date) AS minute,\r\n       COUNT(*) AS count\r\nFROM reports\r\nGROUP BY EXTRACT(MINUTE FROM event_date)\r\nORDER BY minute ASC;"
    }
   ]
  },
  {
   "title": "UFO Sightings by Shape (Pie Chart)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sh.name AS shape_name,\r\n  COUNT(r.shape_id) as shape_count\r\nFROM\r\n  reports r\r\n  LEFT JOIN shapes sh ON r.shape_id = sh.id\r\nGROUP BY shape_name\r\n\r\n"
    }
   ]
  },
  {
   "title": "UFO Sightings by Shape (Bar Chart)",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "rawSql": "SELECT sh.name AS shape_name,\r\nsh.name AS shape_count\r\nFROM reports r\r\nLEFT JOIN shapes sh ON r.shape_id = sh.id"
    }
   ]
  },
  {
   "title": "Denormalized Data",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {
     "rawSql": "SELECT r.id AS report_id,\r\n       r.event_date,\r\n       sh.name AS shape_name,\r\n       co.name AS country_name,\r\n       st.name AS state_name\r\nFROM reports r\r\nLEFT JOIN shapes sh ON r.shape_id = sh.id\r\nLEFT JOIN countries co ON r.country_id = co.id\r\nLEFT JOIN states st ON r.state_id = st.id;"
    }
   ]
  }
 ]
}