apiVersion: 1

datasources:
  - name: Sample_Data
    type: postgres
    typeName: PostgreSQL
    access: proxy
    url: postgres
    user: shoc
    database: sample_data
    basicAuth: false
    isDefault: true
    jsonData:
      postgresVersion: 903
      sslmode: disable
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsConfigurationMethod: file-path
      tlsSkipVerify: true
    secureJsonData:
      password: JustKeepSwimming
    readOnly: false
